### ISSUE TITLE
Firefox version?

### ISSUE THREAD

**Issue by RichardD2** [ericlaw1979/NoLocalHSTS#1]
From what I can see, it should be fairly simple[^1] to make this work in Firefox as well:

[Build a cross-browser extension - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension)

[^1]: I know - famous last words and all that! :)

**Comment by ericlaw1979** [comment]
> From what I can see, it should be fairly simple[1](#user-content-fn-1-dd161971c711cf4d5cce8f71840d7b8b) to make this work in Firefox as well:
> 

Interestingly, it's not needed for Firefox and if my change to chromium lands it won't be needed there anymore either. 

https://x.com/ericlaw/status/1844020102251102553?t=Zamb3YcfjK3isEXOxOmnvg&s=19

**Comment by RichardD2** [comment]
Interesting - that must be a recent change. I'm sure I've hit the localhost + HSTS issue in Firefox before, but it would have been a few years ago.
